import type {JobStatus} from "./api";

export const STATUS = {
  CREATED: "CREATED",
  UPLOAD_READY: "UPLOAD_READY",
  STEP1_RUNNING: "STEP1_RUNNING",
  STEP1_READY: "STEP1_READY",
  STEP1_CONFIRMED: "STEP1_CONFIRMED",
  STEP2_RUNNING: "STEP2_RUNNING",
  STEP2_READY: "STEP2_READY",
  STEP2_CONFIRMED: "STEP2_CONFIRMED",
  RENDER_RUNNING: "RENDER_RUNNING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
} as const;

export const RUNNING_STATUSES = new Set<JobStatus>([
  STATUS.STEP1_RUNNING,
  STATUS.STEP2_RUNNING,
  STATUS.RENDER_RUNNING,
]);

export const DONE_STATUSES = new Set<JobStatus>([
  STATUS.STEP1_CONFIRMED,
  STATUS.STEP2_CONFIRMED,
  STATUS.SUCCEEDED,
]);

export const STEP1_LOADABLE_STATUSES = new Set<JobStatus>([
  STATUS.STEP1_READY,
  STATUS.STEP1_CONFIRMED,
  STATUS.STEP2_RUNNING,
  STATUS.STEP2_READY,
  STATUS.STEP2_CONFIRMED,
  STATUS.RENDER_RUNNING,
  STATUS.SUCCEEDED,
]);

export const STEP2_LOADABLE_STATUSES = new Set<JobStatus>([
  STATUS.STEP2_READY,
  STATUS.STEP2_CONFIRMED,
  STATUS.RENDER_RUNNING,
  STATUS.SUCCEEDED,
]);
