export const STATUS = {
  CREATED: "CREATED",
  UPLOAD_READY: "UPLOAD_READY",
  STEP1_RUNNING: "STEP1_RUNNING",
  STEP1_READY: "STEP1_READY",
  STEP1_CONFIRMED: "STEP1_CONFIRMED",
  STEP2_RUNNING: "STEP2_RUNNING",
  STEP2_READY: "STEP2_READY",
  STEP2_CONFIRMED: "STEP2_CONFIRMED",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
} as const;
