from __future__ import annotations

REMOVE_TOKEN = "<remove>"

ALLOWED_VIDEO_EXTENSIONS = {
    ".mp4",
    ".mov",
    ".mkv",
    ".webm",
    ".m4v",
    ".ts",
    ".m2ts",
    ".mts",
}

ALLOWED_AUDIO_EXTENSIONS = {
    ".m4a",
    ".mp3",
    ".wav",
    ".aac",
    ".flac",
    ".ogg",
    ".opus",
    ".mp4",
}

JOB_STATUS_CREATED = "CREATED"
JOB_STATUS_UPLOAD_READY = "UPLOAD_READY"
JOB_STATUS_TEST_RUNNING = "TEST_RUNNING"
JOB_STATUS_TEST_READY = "TEST_READY"
JOB_STATUS_TEST_CONFIRMED = "TEST_CONFIRMED"
JOB_STATUS_SUCCEEDED = "SUCCEEDED"
JOB_STATUS_FAILED = "FAILED"

JOB_ERROR_CODE_FILES_MISSING = "JOB_FILES_MISSING"
JOB_ERROR_MESSAGE_FILES_MISSING = "当前任务文件已失效或已被清理，请重新上传原视频开始。"

TEST_GET_ALLOWED_STATUSES = frozenset(
    {
        JOB_STATUS_TEST_RUNNING,
        JOB_STATUS_TEST_READY,
        JOB_STATUS_TEST_CONFIRMED,
        JOB_STATUS_SUCCEEDED,
    }
)

RENDER_GET_ALLOWED_STATUSES = frozenset(
    {
        JOB_STATUS_TEST_CONFIRMED,
        JOB_STATUS_SUCCEEDED,
    }
)

PROGRESS_UPLOAD_READY = 10
PROGRESS_TEST_RUNNING = 30
PROGRESS_TEST_READY = 35
PROGRESS_TEST_CONFIRMED = 45
PROGRESS_SUCCEEDED = 100

DEFAULT_ENCODING = "utf-8"
