from __future__ import annotations

REMOVE_TOKEN = "<<REMOVE>>"

ALLOWED_VIDEO_EXTENSIONS = {
    ".mp4",
    ".mov",
    ".mkv",
    ".webm",
    ".m4v",
    ".ts",
    ".m2ts",
    ".mts",
}

JOB_STATUS_CREATED = "CREATED"
JOB_STATUS_UPLOAD_READY = "UPLOAD_READY"
JOB_STATUS_STEP1_RUNNING = "STEP1_RUNNING"
JOB_STATUS_STEP1_READY = "STEP1_READY"
JOB_STATUS_STEP1_CONFIRMED = "STEP1_CONFIRMED"
JOB_STATUS_STEP2_RUNNING = "STEP2_RUNNING"
JOB_STATUS_STEP2_READY = "STEP2_READY"
JOB_STATUS_STEP2_CONFIRMED = "STEP2_CONFIRMED"
JOB_STATUS_RENDER_RUNNING = "RENDER_RUNNING"
JOB_STATUS_SUCCEEDED = "SUCCEEDED"
JOB_STATUS_FAILED = "FAILED"

STEP1_GET_ALLOWED_STATUSES = frozenset(
    {
        JOB_STATUS_STEP1_READY,
        JOB_STATUS_STEP1_CONFIRMED,
        JOB_STATUS_STEP2_RUNNING,
        JOB_STATUS_STEP2_READY,
        JOB_STATUS_STEP2_CONFIRMED,
        JOB_STATUS_RENDER_RUNNING,
        JOB_STATUS_SUCCEEDED,
    }
)

STEP2_GET_ALLOWED_STATUSES = frozenset(
    {
        JOB_STATUS_STEP2_READY,
        JOB_STATUS_STEP2_CONFIRMED,
        JOB_STATUS_SUCCEEDED,
    }
)

RENDER_GET_ALLOWED_STATUSES = frozenset(
    {
        JOB_STATUS_STEP2_CONFIRMED,
        JOB_STATUS_RENDER_RUNNING,
        JOB_STATUS_SUCCEEDED,
    }
)

TASK_TYPE_STEP1 = "STEP1"
TASK_TYPE_STEP2 = "STEP2"
TASK_TYPE_RENDER = "RENDER"

TASK_STATUS_QUEUED = "QUEUED"
TASK_STATUS_RUNNING = "RUNNING"
TASK_STATUS_SUCCEEDED = "SUCCEEDED"
TASK_STATUS_FAILED = "FAILED"

PROGRESS_UPLOAD_READY = 10
PROGRESS_STEP1_RUNNING = 30
PROGRESS_STEP1_READY = 35
PROGRESS_STEP2_RUNNING = 60
PROGRESS_STEP2_READY = 75
PROGRESS_STEP1_CONFIRMED = 45
PROGRESS_STEP2_CONFIRMED = 80
PROGRESS_RENDER_RUNNING = 0
PROGRESS_SUCCEEDED = 100

DEFAULT_ENCODING = "utf-8"
